# Generated by Django 5.0.2 on 2026-02-16 09:37

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the employee', primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Employee's full name", max_length=255)),
                ('phone', models.CharField(help_text="Employee's phone number", max_length=20)),
                ('email', models.EmailField(help_text="Employee's email address", max_length=254)),
                ('employer_name', models.CharField(help_text='Name of the employer/company', max_length=255)),
                ('position', models.CharField(help_text="Employee's job position", max_length=255)),
                ('reputation_score', models.FloatField(help_text='Reputation score (0-10)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the employee', null=True)),
                ('image', models.ImageField(help_text="Employee's photo for facial recognition", upload_to='employee_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the employee was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the employee was last updated')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['full_name'], name='employees_e_full_na_997ac1_idx'), models.Index(fields=['employer_name'], name='employees_e_employe_2f460b_idx'), models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx')],
            },
        ),
    ]
